// <auto-generated />
using System;
using BeeSoft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeSoft.Data.Migrations
{
    [DbContext(typeof(BeeSoftDbContext))]
    [Migration("20240115134020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeeSoft.Data.Models.Apiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ProbableEndOfHoneyCollectionPeriod")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartOfHoneyCollectionPeriod")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalHoneyHarvested")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Apiaries");
                });

            modelBuilder.Entity("BeeSoft.Data.Models.BeeQueen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BeehiveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BeehiveId");

                    b.ToTable("BeeQueens");
                });

            modelBuilder.Entity("BeeSoft.Data.Models.Beehive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiaryId")
                        .HasColumnType("int");

                    b.Property<int?>("BeeQueenId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateBought")
                        .HasColumnType("date");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApiaryId");

                    b.HasIndex("BeeQueenId");

                    b.ToTable("Beehives");
                });

            modelBuilder.Entity("BeeSoft.Data.Models.BeeQueen", b =>
                {
                    b.HasOne("BeeSoft.Data.Models.Beehive", "Beehive")
                        .WithMany()
                        .HasForeignKey("BeehiveId");

                    b.Navigation("Beehive");
                });

            modelBuilder.Entity("BeeSoft.Data.Models.Beehive", b =>
                {
                    b.HasOne("BeeSoft.Data.Models.Apiary", "Apiary")
                        .WithMany("Beehives")
                        .HasForeignKey("ApiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeSoft.Data.Models.BeeQueen", "BeeQueen")
                        .WithMany()
                        .HasForeignKey("BeeQueenId");

                    b.Navigation("Apiary");

                    b.Navigation("BeeQueen");
                });

            modelBuilder.Entity("BeeSoft.Data.Models.Apiary", b =>
                {
                    b.Navigation("Beehives");
                });
#pragma warning restore 612, 618
        }
    }
}
